package scan

import (
	"testing"
)

var want map[string]string = map[string]string{
	"fluent-plugin-kafka":         "0.17.5",
	"http":                        "4.4.1",
	"mini_mime":                   "1.1.2",
	"oj":                          "3.13.11",
	"digest-crc":                  "0.6.4",
	"mime-types":                  "3.4.1",
	"protocol-http1":              "0.14.4",
	"faraday-rack":                "1.0.0",
	"fluent-plugin-remote-syslog": "1.1",
	"protocol-hpack":              "1.4.2",
	"swd":                         "1.3.0",
	"console":                     "1.15.0",
	"net-http-persistent":         "4.0.1",
	"webfinger":                   "1.2.0",
	"zeitwerk":                    "2.5.4",
	"serverengine":                "2.2.5",
	"async":                       "1.30.2",
	"faraday-em_synchrony":        "1.0.0",
	"faraday-patron":              "1.0.0",
	"fluent-plugin-prometheus":    "2.0.3",
	"public_suffix":               "4.0.7",
	"rest-client":                 "2.1.0",
	"bigdecimal":                  "3.1.2",
	"faraday-httpclient":          "1.0.1",
	"json-jwt":                    "1.13.0",
	"jsonpath":                    "1.1.2",
	"rack":                        "2.2.3",
	"systemd-journal":             "1.4.2",
	"async-http":                  "0.56.6",
	"i18n":                        "1.10.0",
	"aws-sdk-cloudwatchlogs":      "1.52.0",
	"minitest":                    "5.15.0",
	"fluent-plugin-label-router":  "0.2.10",
	"kubeclient":                  "4.9.3",
	"excon":                       "0.92.3",
	"ffi":                         "1.15.5",
	"fluent-plugin-systemd":       "1.0.5",
	"fluent-plugin-kubernetes_metadata_filter": "3.0.1",
	"mail":                              "2.7.1",
	"validate_email":                    "0.1.6",
	"fluent-plugin-splunk-hec":          "1.2.13",
	"unf":                               "0.1.4",
	"faraday-multipart":                 "1.0.3",
	"faraday-net_http_persistent":       "1.2.0",
	"mime-types-data":                   "3.2022.0105",
	"rake":                              "13.0.6",
	"fluent-plugin-rewrite-tag-filter":  "2.4.0",
	"jmespath":                          "1.6.1",
	"multipart-post":                    "2.1.1",
	"ruby2_keywords":                    "0.0.5",
	"faraday-net_http":                  "1.0.1",
	"fluent-plugin-concat":              "2.5.0",
	"fluent-plugin-elasticsearch":       "5.2.2",
	"fluent-plugin-record-modifier":     "2.1.0",
	"validate_url":                      "1.0.13",
	"activesupport":                     "6.1.6",
	"aws-partitions":                    "1.586.0",
	"ltsv":                              "0.1.2",
	"openid_connect":                    "1.1.8",
	"nio4r":                             "2.5.8",
	"unf_ext":                           "0.0.8.1",
	"webrick":                           "1.7.0",
	"attr_required":                     "1.0.1",
	"fluent-plugin-cloudwatch-logs":     "0.14.2",
	"fluentd":                           "1.14.6",
	"prometheus-client":                 "4.0.0",
	"async-pool":                        "0.3.10",
	"fluent-mixin-config-placeholders":  "0.4.0",
	"yajl-ruby":                         "1.4.1",
	"activemodel":                       "6.1.6",
	"protocol-http":                     "0.22.6",
	"timers":                            "4.3.3",
	"traces":                            "0.4.1",
	"addressable":                       "2.8.0",
	"elasticsearch-api":                 "7.17.1",
	"fluent-config-regexp-type":         "1.0.0",
	"fluent-plugin-detect-exceptions":   "0.0.14",
	"connection_pool":                   "2.2.5",
	"domain_name":                       "0.5.20190701",
	"netrc":                             "0.11.0",
	"uuidtools":                         "2.2.0",
	"ffi-compiler":                      "1.0.1",
	"http-form_data":                    "2.3.0",
	"msgpack":                           "1.5.1",
	"multi_json":                        "1.15.0",
	"ruby-kafka":                        "1.4.0",
	"tzinfo":                            "2.0.4",
	"tzinfo-data":                       "1.2022.1",
	"aws-sdk-core":                      "3.130.2",
	"concurrent-ruby":                   "1.1.10",
	"elasticsearch":                     "7.17.1",
	"fluent-plugin-multi-format-parser": "1.0.0",
	"sigdump":                           "0.2.4",
	"aes_key_wrap":                      "1.1.0",
	"async-io":                          "1.33.0",
	"http-accept":                       "1.7.0",
	"httpclient":                        "2.8.3",
	"http-parser":                       "1.2.3",
	"faraday-em_http":                   "1.0.0",
	"faraday-retry":                     "1.0.3",
	"fiber-local":                       "1.0.0",
	"http-cookie":                       "1.0.4",
	"ethon":                             "0.15.0",
	"fluent-plugin-grafana-loki":        "1.2.18",
	"rack-oauth2":                       "1.19.0",
	"strptime":                          "0.2.5",
	"aws-sigv4":                         "1.5.0",
	"cool.io":                           "1.7.1",
	"lru_redux":                         "1.1.0",
	"elasticsearch-transport":           "7.17.1",
	"faraday-excon":                     "1.1.0",
	"aws-eventstream":                   "1.2.0",
	"http_parser.rb":                    "0.8.0",
	"recursive-open-struct":             "1.1.3",
	"syslog_protocol":                   "0.9.2",
	"protocol-http2":                    "0.14.2",
	"typhoeus":                          "1.4.0",
	"bindata":                           "2.4.10",
	"faraday":                           "1.10.0",
}

func Test_GetRubyDeps(t *testing.T) {
	got, err := GetRubyDeps("../../test/testRepo/")

	if err != nil {
		t.Errorf("GetRubyDeps() error thrown: %+v", err)
	}

	for k, v := range want {
		if got[k] != v {
			t.Errorf("GetRubyDeps() - deps missing entry: %s = %s ", k, v)
		}
	}

	if len(got) != len(want) {
		t.Errorf("GetRubyDeps() = %d; want %d", len(got), len(want))
	}
}
